language: python
python:
  - "3.8"
env:
  - SECRET_KEY=somethinghereforciprtoexecuteintestbuilds
install:
  - pip install pipenv --upgrade-strategy=only-if-needed
  - pipenv install --dev
  - cp .env.example .env
script: pytest
